"""Provider/model/auth selection without an agent runtime."""

from .access import (
    DEFAULT_TERMS_POSTURE,
    TERMS_POSTURES,
    AccessRoute,
    ProviderAccess,
    provider_access,
    provider_access_routes,
)
from .auth import (
    AuthBroker,
    CredentialLease,
    CredentialMaterial,
    EnvironmentSecretStore,
    KeyringSecretStore,
    MemorySecretStore,
    SecretStore,
)
from .broker import (
    CredentialBroker,
    CredentialResolution,
    CredentialSnapshot,
    RuntimeCredential,
)
from .catalog import Catalog, ModelsDevSource, SearchHit, load_overlay
from .contracts import (
    AuthMethod,
    CatalogSnapshot,
    CredentialProfile,
    ModelSpec,
    ModelVariant,
    ProviderSpec,
    SelectionIntent,
    SelectionPlan,
)
from .discovery import discover_environment_profiles
from .gateway import (
    GatewayRecord,
    GatewayRoute,
    InferenceGateway,
    gateway_routes,
    gateway_server,
    make_gateway_handler,
    provider_gateway_routes,
    serve_gateway,
)
from .login import (
    THIRD_PARTY_CLIENT_DRIVERS,
    ChoicePrompt,
    LoginBroker,
    LoginDriver,
    LoginResult,
    LoginSession,
    OpenUrlPrompt,
    SecretPrompt,
    UserCodePrompt,
    permits_third_party_client,
    permitted_drivers,
)
from .oauth import (
    AuthorizationPending,
    AuthorizationRequest,
    DeviceAuthorization,
    OAuthClient,
    OAuthError,
    OAuthProviderConfig,
)
from .oauth_login import (
    LoopbackRedirect,
    OAuthDeviceDriver,
    OAuthPkceDriver,
    route_oauth_config,
)
from .pool import POOL_STRATEGIES, CredentialPool
from .popularity import (
    POPULAR_PROVIDER_IDS,
    provider_popularity_key,
    provider_popularity_rank,
)
from .probe import (
    Prober,
    ProbeResult,
    entitlement_for,
    gateway_probe_driver,
    gateway_probe_drivers,
)
from .profiles import ProfileRegistry
from .selection import Selector

__all__ = [
    "DEFAULT_TERMS_POSTURE",
    "POOL_STRATEGIES",
    "POPULAR_PROVIDER_IDS",
    "TERMS_POSTURES",
    "THIRD_PARTY_CLIENT_DRIVERS",
    "AccessRoute",
    "AuthBroker",
    "AuthMethod",
    "AuthorizationPending",
    "AuthorizationRequest",
    "Catalog",
    "CatalogSnapshot",
    "ChoicePrompt",
    "CredentialBroker",
    "CredentialLease",
    "CredentialMaterial",
    "CredentialPool",
    "CredentialProfile",
    "CredentialResolution",
    "CredentialSnapshot",
    "DeviceAuthorization",
    "EnvironmentSecretStore",
    "GatewayRecord",
    "GatewayRoute",
    "InferenceGateway",
    "KeyringSecretStore",
    "LoginBroker",
    "LoginDriver",
    "LoginResult",
    "LoginSession",
    "LoopbackRedirect",
    "MemorySecretStore",
    "ModelSpec",
    "ModelVariant",
    "ModelsDevSource",
    "OAuthClient",
    "OAuthDeviceDriver",
    "OAuthError",
    "OAuthPkceDriver",
    "OAuthProviderConfig",
    "OpenUrlPrompt",
    "ProbeResult",
    "Prober",
    "ProfileRegistry",
    "ProviderAccess",
    "ProviderSpec",
    "RuntimeCredential",
    "SearchHit",
    "SecretPrompt",
    "SecretStore",
    "SelectionIntent",
    "SelectionPlan",
    "Selector",
    "UserCodePrompt",
    "discover_environment_profiles",
    "entitlement_for",
    "gateway_probe_driver",
    "gateway_probe_drivers",
    "gateway_routes",
    "gateway_server",
    "load_overlay",
    "make_gateway_handler",
    "permits_third_party_client",
    "permitted_drivers",
    "provider_access",
    "provider_access_routes",
    "provider_gateway_routes",
    "provider_popularity_key",
    "provider_popularity_rank",
    "route_oauth_config",
    "serve_gateway",
]
